<h1 style="font-size: 32px; text-align: center;">Introduction to Computer Programming for the Physical Sciences</h1>
<h2 style="font-size: 24px; text-align: center;">Shane Bechtel</h2>
<h3 style="font-size: 24px; text-align: center;">Spring 2024</h2>

## Working on Section Problems

<ul style="list-style: none;">
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Get into groups of 2 or 3, with at least one laptop per group.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Discuss with each other and attempt each problem yourselves first without AI support for 10-15 mins.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>Input the problem prompt into the AI chatbox, use its answer to verify your own, or to learn how it should be solved.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;">
</span>For section problems, you can omit most of the commenting and focus on learning coding. For more difficult problems, minimal comments are still recommended as a way of organizing your own thoughts.</li>
  <li style="margin-bottom: 10px; font-size: 20px;"><span style="display: inline-block; width: 10px; height: 10px; border: 2px solid black; margin-right: 10px;"></span>Please abide by the <b><a href="https://github.com/enigma-igm/Phys29/blob/main/using_AI_tools.md">Policy and Guidelines on Using AI Tools</a></b></li>

# Section 4

In [2]:
import numpy as np

## Problem 1

1. Write a function with a for loop inside it to return the factorial of x, f (x) = x!, where x is passed in as an argument.

2. Write a function using recursion to return the factorial of an argument, f (x) = x!, by implementing the recursion relation f (0) = 1, f (n) = nf (n − 1).

In [3]:
# your solution here
sum = 1
for i in range(3):
    sum = sum*(i+1)
print(sum)

def factorial(x):
    if(x==0):
        return 1
    return x*factorial(x-1)

factorial(3)

6


6

## Problem 2

Compute the sum of the even numbers between 2 and 100 (inclusive) four ways:

• Use a for loop over the integers
    
• Create an array from 2 to 100 using numpy.arange() with a step size of 2, then
sum it using numpy.sum()

• Create an array from 1 to 50 using numpy.arange(), double it, and sum it

• Create an array from 0 to 100 and take every second element, then sum it

In [4]:
# your solution here
sum = 0
for i in range(100):
    if((i+1)%2 == 0):
        sum = sum + i+1
print(sum)

a = np.arange(2,101,2,int)
print(np.sum(a))

a = np.arange(1,51,1,int)
print(2*np.sum(a))

a = np.arange(0,101,2,int)
print(np.sum(a))

2550
2550
2550
2550


## Problem 3

Generate 5 random number from a Gaussian distribution of mean 6 and standard deviation 3. (Google numpy functions and find the right ones to use)

In [5]:
# your solution here
print(np.random.normal(6,3,5))

[13.21763     1.19169165  2.21098424  5.92321468  9.15764124]


## Problem 4

This problem will give a very brief introduction to multidimensional arrays.

• Using np.array, create a 3 × 3 numpy array called x with first row 0, 1, and 2; second row 3, 4, and 5; and third row 6, 7, and 8.

• Do the same thing by first creating a one dimensional array of nine elements using np.arange, and then np.reshape; the new shape will be (3, 3).

• How do you index the central element 4 of your 3 × 3 array x?

• For multidimensional arrays, np.sum can also take an argument known as axis. Execute the following code on your 3 × 3 array x:
```
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
```
What does np.sum with no axis argument do? What are the axis=0 and axis=1 arguments doing?

In [10]:
# your solution here

x = np.array([[0,1,2],[3,4,5 ],[6,7,8]])
print(np.sum(x))
x = np.arange(0,9,1,int)
x = np.reshape(x,(3,3))
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

36
[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
[ 9 12 15]
[ 3 12 21]
